namespace LittleConqueror.AppService.Domain.Models;

public enum TechnologiqueResearch
{
    // Miltaire
    Armement_I = 0,
    Armement_II = 1,
    Armement_III = 2,
    Poudre_A_Canon = 3,
    Armement_IV = 4,
    Arme_Atomique = 5,
    // GeoPolitique
    Classement = 6,
    Politique = 7,
    Alliance = 8,
    Guerre = 9,
    Espionnage = 10,
    Echanges = 11,
    Traite_De_Paix = 12,
    // Theorie
    Gribouillis = 13,
    Roue = 14,
    Ecriture = 15,
    Apprentissage = 16,
    Ecoles = 17,
    Mathematiques = 18,
    Monnaie = 19,
    Physiques = 20,
    Explosion = 21,
    Traitement_Des_Fluides = 22,
    Forage = 23,
    Projet_Manhattan = 24,
    Financement_Mondiale_Future_I = 25,
    Financement_Mondiale_Future_II = 26,
    Financement_Mondiale_Future_III = 27,
    Financement_Mondiale_Future_IV = 28,
    Skills_Sellers = 29,
    // Ingenierie
    Pierre = 30,
    Rendement_Minier_I = 31,
    Rendement_Agricole_I = 32,
    Fer = 33,
    Rendement_Minier_II = 34,
    Rendement_Agricole_II = 35,
    Routes = 36,
    Chemins_De_Fer = 37,
    Or = 38,
    Electricite = 39,
    Diamant = 40,
    Rendement_Minier_III = 41,
    Rendement_Agricole_III = 42,
    Petrole = 43,
    Carburant = 44,
    Fission_Nucleaire = 45,
    Fusion_Nucleaire = 46,
    Tesseract_Energetique = 47,
    Rendement_Scientifique_I = 48,
    Rendement_Scientifique_II = 49,
    Rendement_Scientifique_III = 50,
    Rendement_Scientifique_IV = 51,
    Technologies_Futures = 52,
    Mode_Creatif = 53
}